In [19]:
#importing requied libraries.
import pandas as pd
import numpy as np
from sklearn import datasets
dataset=datasets.load_iris()

data=pd.DataFrame(dataset['data'],columns=['Petal length','Petal Width','Sepal Length','Sepal Width'])
data['Species']=dataset['target']
data['Species']=data['Species'].apply(lambda x: dataset['target_names'][x])

In [22]:
data.head()

Petal length  Petal Width  Sepal Length  Sepal Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [23]:
data.describe()

Petal length  Petal Width  Sepal Length  Sepal Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [24]:
data.isnull().sum()

Petal length    0
Petal Width     0
Sepal Length    0
Sepal Width     0
Species         0
dtype: int64

In [26]:
modData = data.append({'Petal length' : np.nan , 'Petal Width' : 3.6, 'Sepal Length': 0,

            'Sepal Width': 0.2, 'Species': 'setosa' } , ignore_index=True)

In [27]:
modData.describe()

Petal length  Petal Width  Sepal Length  Sepal Width
count    150.000000   151.000000    151.000000   151.000000
mean       5.843333     3.060927      3.733113     1.192715
std        0.828066     0.436650      1.785785     0.764033
min        4.300000     2.000000      0.000000     0.100000
25%        5.100000     2.800000      1.550000     0.300000
50%        5.800000     3.000000      4.300000     1.300000
75%        6.400000     3.350000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [28]:
modData.isnull().sum()

Petal length    1
Petal Width     0
Sepal Length    0
Sepal Width     0
Species         0
dtype: int64

In [29]:
print('Columns with missing values')
print(modData.isnull().sum())
print('\n Columns with zero values')
print((modData[['Petal length' , 'Petal Width' , 'Sepal Length' , 'Sepal Width' , 'Species']]==0).sum())

Columns with missing values
Petal length    1
Petal Width     0
Sepal Length    0
Sepal Width     0
Species         0
dtype: int64

 Columns with zero values
Petal length    0
Petal Width     0
Sepal Length    1
Sepal Width     0
Species         0
dtype: int64


In [31]:
modData[['Petal length',

     'Petal Width',

     'Sepal Length',

     'Sepal Width','Species']] = modData[['Petal length',

                       'Petal Width',

                       'Sepal Length',

                       'Sepal Width',

                       'Species']].replace(0, np.NaN)

print('Columns with missing values')
print(modData.isnull().sum())

Columns with missing values
Petal length    1
Petal Width     0
Sepal Length    1
Sepal Width     0
Species         0
dtype: int64


In [32]:
modData.fillna(modData.mean(), inplace=True)

In [33]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# load dataset into Pandas DataFrame



PCA_df = pd.read_csv(url, names=['Sepal Length' , 'Sepal Width' , 'Petal length' , 'Petal Width' , 'target'])
PCA_df.head()

Sepal Length  Sepal Width  Petal length  Petal Width       target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [49]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

features = ['Sepal Length' , 'Sepal Width' , 'Petal length' , 'Petal Width']

# Separating out the features

x = PCA_df.loc[:, features].values

# Separating out the target

y = PCA_df.loc[:,['target']].values

# Standardizing the features

x = MinMaxScaler().fit_transform(x)

print (x)

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

In [55]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

principalComponents = pca.fit_transform(x)

principalDf = pd.DataFrame(data = principalComponents

       , columns = ['principal component 1', 'principal component 2'])

In [56]:
print(principalDf)

     principal component 1  principal component 2
0                -0.630361               0.111556
1                -0.623546              -0.100313
2                -0.669793              -0.047220
3                -0.654633              -0.098791
4                -0.648263               0.137558
..                     ...                    ...
145               0.551755               0.058990
146               0.406278              -0.172227
147               0.447293               0.036996
148               0.489218               0.149121
149               0.312079              -0.031151

[150 rows x 2 columns]


In [59]:
finalDf = pd.concat([principalDf, PCA_df[['target']]], axis = 1)
print (principalDf)

     principal component 1  principal component 2
0                -0.630361               0.111556
1                -0.623546              -0.100313
2                -0.669793              -0.047220
3                -0.654633              -0.098791
4                -0.648263               0.137558
..                     ...                    ...
145               0.551755               0.058990
146               0.406278              -0.172227
147               0.447293               0.036996
148               0.489218               0.149121
149               0.312079              -0.031151

[150 rows x 2 columns]


In [60]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

4:09 PM
features = ['sepal length', 'sepal width', 'petal length', 'petal width']

# Separating out the features

x = PCA_df.loc[:, features].values

# Separating out the target

y = PCA_df.loc[:,['target']].values

# Standardizing the features

x = StandardScaler().fit_transform(x)

print (x)

4:13 PM
[: , ]

4:23 PM
from sklearn.decomposition import PCA

4:23 PM
pca = PCA(n_components=2)

4:25 PM
principalComponents = pca.fit_transform(x)

4:26 PM
principalDf = pd.DataFrame(data = principalComponents

       , columns = ['principal component 1', 'principal component 2'])

4:27 PM
finalDf = pd.concat([principalDf, PCA_df[['target']]], axis = 1)

4:33 PM
import matplotlib.pyplot as plt

%matplotlib inline

#sns.set(color_codes=True)



fig = plt.figure(figsize = (8,8))

ax = fig.add_subplot(1,1,1) 

ax.set_xlabel('Principal Component 1', fontsize = 15)

ax.set_ylabel('Principal Component 2', fontsize = 15)

ax.set_title('2 component PCA', fontsize = 20)

targets = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

colors = ['r', 'g', 'b']

for target, color in zip(targets,colors):

  indicesToKeep = finalDf['target'] == target

  ax.scatter(finalDf.loc[indicesToKeep, 'principal component 1']

        , finalDf.loc[indicesToKeep, 'principal component 2']

        , c = color

        , s = 50)

ax.legend(targets)

ax.grid()

4:44 PM
print(pca.explained_variance_ratio_)

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (<ipython-input-60-1f45a849c0bc>, line 3)